language: node_js

node_js:
  - "v10.15.3"

cache:
  directories:
    - node_modules

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE barefootNomad_test;" -U postgres
  - psql -c "ALTER ROLE postgres PASSWORD 'postgres';" -U postgres

script:
  - npm test

after_success:
  - npm run coverage
  - npm run undo:migration
