language: node_js

node_js:
  - 10.15.3

cache:
  directories:
    - node_modules

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE barefootNomad_test;" -U postgres
  - psql -c "ALTER ROLE postgres PASSWORD 'postgres';" -U postgres
  - touch src/logs/app.log

script:
  - npm run db:migrate
  - npm test

after_success:
  - npm run coverage
  - npm run undo:migration
