language: node_js

node_js:
  - "v10.15.3"

cache:
  directories:
    - node_modules

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres

script:
  - npm test
