version: "3.7"

services:
  webapp:
    container_name: barefoot-nomad
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume:
